export const TYPES = {
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_ONE_FROM_CART: "DELETE_ONE_FROM_CART",
    DELETE_ALL_FROM_CART: "DELETE_ALL_FROM_CART",
    CLEAR_CART: "CLEAR_CART",
    CALCULATE_PRICE: "CALCULATE_PRICE"
}